// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: modelfile-v2.proto

package v2

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _modelfile_v_2_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on ModelFile with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ModelFile) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModelFile with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ModelFileMultiError, or nil
// if none found.
func (m *ModelFile) ValidateAll() error {
	return m.validate(true)
}

func (m *ModelFile) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetProtocolVersion()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModelFileValidationError{
					field:  "ProtocolVersion",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModelFileValidationError{
					field:  "ProtocolVersion",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProtocolVersion()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModelFileValidationError{
				field:  "ProtocolVersion",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for CreatedAt

	if m.GetFileInfo() == nil {
		err := ModelFileValidationError{
			field:  "FileInfo",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetFileInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModelFileValidationError{
					field:  "FileInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModelFileValidationError{
					field:  "FileInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFileInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModelFileValidationError{
				field:  "FileInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetFileContent() == nil {
		err := ModelFileValidationError{
			field:  "FileContent",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetFileContent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModelFileValidationError{
					field:  "FileContent",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModelFileValidationError{
					field:  "FileContent",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFileContent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModelFileValidationError{
				field:  "FileContent",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(m.GetClassLabels()) < 1 {
		err := ModelFileValidationError{
			field:  "ClassLabels",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetClassLabels() {
		_, _ = idx, item

		if item == nil {
			err := ModelFileValidationError{
				field:  fmt.Sprintf("ClassLabels[%v]", idx),
				reason: "value is required",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ModelFileValidationError{
						field:  fmt.Sprintf("ClassLabels[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ModelFileValidationError{
						field:  fmt.Sprintf("ClassLabels[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ModelFileValidationError{
					field:  fmt.Sprintf("ClassLabels[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetInputDecodingInformation()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModelFileValidationError{
					field:  "InputDecodingInformation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModelFileValidationError{
					field:  "InputDecodingInformation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInputDecodingInformation()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModelFileValidationError{
				field:  "InputDecodingInformation",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetOutputDecodingInformation()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModelFileValidationError{
					field:  "OutputDecodingInformation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModelFileValidationError{
					field:  "OutputDecodingInformation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOutputDecodingInformation()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModelFileValidationError{
				field:  "OutputDecodingInformation",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ModelFileMultiError(errors)
	}

	return nil
}

// ModelFileMultiError is an error wrapping multiple validation errors returned
// by ModelFile.ValidateAll() if the designated constraints aren't met.
type ModelFileMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelFileMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelFileMultiError) AllErrors() []error { return m }

// ModelFileValidationError is the validation error returned by
// ModelFile.Validate if the designated constraints aren't met.
type ModelFileValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelFileValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModelFileValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModelFileValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModelFileValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModelFileValidationError) ErrorName() string { return "ModelFileValidationError" }

// Error satisfies the builtin error interface
func (e ModelFileValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModelFile.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelFileValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelFileValidationError{}

// Validate checks the field values on ModelFile_Version with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ModelFile_Version) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModelFile_Version with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ModelFile_VersionMultiError, or nil if none found.
func (m *ModelFile_Version) ValidateAll() error {
	return m.validate(true)
}

func (m *ModelFile_Version) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Major

	// no validation rules for Minor

	// no validation rules for Patch

	if len(errors) > 0 {
		return ModelFile_VersionMultiError(errors)
	}

	return nil
}

// ModelFile_VersionMultiError is an error wrapping multiple validation errors
// returned by ModelFile_Version.ValidateAll() if the designated constraints
// aren't met.
type ModelFile_VersionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelFile_VersionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelFile_VersionMultiError) AllErrors() []error { return m }

// ModelFile_VersionValidationError is the validation error returned by
// ModelFile_Version.Validate if the designated constraints aren't met.
type ModelFile_VersionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelFile_VersionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModelFile_VersionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModelFile_VersionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModelFile_VersionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModelFile_VersionValidationError) ErrorName() string {
	return "ModelFile_VersionValidationError"
}

// Error satisfies the builtin error interface
func (e ModelFile_VersionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModelFile_Version.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelFile_VersionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelFile_VersionValidationError{}

// Validate checks the field values on ModelFile_Content with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ModelFile_Content) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModelFile_Content with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ModelFile_ContentMultiError, or nil if none found.
func (m *ModelFile_Content) ValidateAll() error {
	return m.validate(true)
}

func (m *ModelFile_Content) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetByteContent()) < 1 {
		err := ModelFile_ContentValidationError{
			field:  "ByteContent",
			reason: "value length must be at least 1 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetHashSha256()) < 1 {
		err := ModelFile_ContentValidationError{
			field:  "HashSha256",
			reason: "value length must be at least 1 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := ModelFile_Content_CompressionMethod_name[int32(m.GetCompressionMethod())]; !ok {
		err := ModelFile_ContentValidationError{
			field:  "CompressionMethod",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := ModelFile_Content_EncryptionMethod_name[int32(m.GetEncryptionMethod())]; !ok {
		err := ModelFile_ContentValidationError{
			field:  "EncryptionMethod",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	{
		sorted_keys := make([]string, len(m.GetKeySlots()))
		i := 0
		for key := range m.GetKeySlots() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetKeySlots()[key]
			_ = val

			// no validation rules for KeySlots[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, ModelFile_ContentValidationError{
							field:  fmt.Sprintf("KeySlots[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, ModelFile_ContentValidationError{
							field:  fmt.Sprintf("KeySlots[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return ModelFile_ContentValidationError{
						field:  fmt.Sprintf("KeySlots[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	if len(errors) > 0 {
		return ModelFile_ContentMultiError(errors)
	}

	return nil
}

// ModelFile_ContentMultiError is an error wrapping multiple validation errors
// returned by ModelFile_Content.ValidateAll() if the designated constraints
// aren't met.
type ModelFile_ContentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelFile_ContentMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelFile_ContentMultiError) AllErrors() []error { return m }

// ModelFile_ContentValidationError is the validation error returned by
// ModelFile_Content.Validate if the designated constraints aren't met.
type ModelFile_ContentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelFile_ContentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModelFile_ContentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModelFile_ContentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModelFile_ContentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModelFile_ContentValidationError) ErrorName() string {
	return "ModelFile_ContentValidationError"
}

// Error satisfies the builtin error interface
func (e ModelFile_ContentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModelFile_Content.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelFile_ContentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelFile_ContentValidationError{}

// Validate checks the field values on ModelFile_ClassLabel with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ModelFile_ClassLabel) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModelFile_ClassLabel with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ModelFile_ClassLabelMultiError, or nil if none found.
func (m *ModelFile_ClassLabel) ValidateAll() error {
	return m.validate(true)
}

func (m *ModelFile_ClassLabel) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetClassLabelId()); err != nil {
		err = ModelFile_ClassLabelValidationError{
			field:  "ClassLabelId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Name

	// no validation rules for ShortName

	if !_ModelFile_ClassLabel_Color_Pattern.MatchString(m.GetColor()) {
		err := ModelFile_ClassLabelValidationError{
			field:  "Color",
			reason: "value does not match regex pattern \"^#(?:[0-9a-fA-F]{2}){3}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ModelFile_ClassLabelMultiError(errors)
	}

	return nil
}

func (m *ModelFile_ClassLabel) _validateUuid(uuid string) error {
	if matched := _modelfile_v_2_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// ModelFile_ClassLabelMultiError is an error wrapping multiple validation
// errors returned by ModelFile_ClassLabel.ValidateAll() if the designated
// constraints aren't met.
type ModelFile_ClassLabelMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelFile_ClassLabelMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelFile_ClassLabelMultiError) AllErrors() []error { return m }

// ModelFile_ClassLabelValidationError is the validation error returned by
// ModelFile_ClassLabel.Validate if the designated constraints aren't met.
type ModelFile_ClassLabelValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelFile_ClassLabelValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModelFile_ClassLabelValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModelFile_ClassLabelValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModelFile_ClassLabelValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModelFile_ClassLabelValidationError) ErrorName() string {
	return "ModelFile_ClassLabelValidationError"
}

// Error satisfies the builtin error interface
func (e ModelFile_ClassLabelValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModelFile_ClassLabel.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelFile_ClassLabelValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelFile_ClassLabelValidationError{}

var _ModelFile_ClassLabel_Color_Pattern = regexp.MustCompile("^#(?:[0-9a-fA-F]{2}){3}$")

// Validate checks the field values on ModelFile_ImageSize with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ModelFile_ImageSize) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModelFile_ImageSize with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ModelFile_ImageSizeMultiError, or nil if none found.
func (m *ModelFile_ImageSize) ValidateAll() error {
	return m.validate(true)
}

func (m *ModelFile_ImageSize) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetWidth() <= 0 {
		err := ModelFile_ImageSizeValidationError{
			field:  "Width",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetHeight() <= 0 {
		err := ModelFile_ImageSizeValidationError{
			field:  "Height",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetChannels() <= 0 {
		err := ModelFile_ImageSizeValidationError{
			field:  "Channels",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ModelFile_ImageSizeMultiError(errors)
	}

	return nil
}

// ModelFile_ImageSizeMultiError is an error wrapping multiple validation
// errors returned by ModelFile_ImageSize.ValidateAll() if the designated
// constraints aren't met.
type ModelFile_ImageSizeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelFile_ImageSizeMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelFile_ImageSizeMultiError) AllErrors() []error { return m }

// ModelFile_ImageSizeValidationError is the validation error returned by
// ModelFile_ImageSize.Validate if the designated constraints aren't met.
type ModelFile_ImageSizeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelFile_ImageSizeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModelFile_ImageSizeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModelFile_ImageSizeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModelFile_ImageSizeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModelFile_ImageSizeValidationError) ErrorName() string {
	return "ModelFile_ImageSizeValidationError"
}

// Error satisfies the builtin error interface
func (e ModelFile_ImageSizeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModelFile_ImageSize.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelFile_ImageSizeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelFile_ImageSizeValidationError{}

// Validate checks the field values on ModelFile_RegionFromEdge with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ModelFile_RegionFromEdge) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModelFile_RegionFromEdge with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ModelFile_RegionFromEdgeMultiError, or nil if none found.
func (m *ModelFile_RegionFromEdge) ValidateAll() error {
	return m.validate(true)
}

func (m *ModelFile_RegionFromEdge) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if val := m.GetLeft(); val < 0 || val >= 1 {
		err := ModelFile_RegionFromEdgeValidationError{
			field:  "Left",
			reason: "value must be inside range [0, 1)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetRight(); val < 0 || val >= 1 {
		err := ModelFile_RegionFromEdgeValidationError{
			field:  "Right",
			reason: "value must be inside range [0, 1)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetTop(); val < 0 || val >= 1 {
		err := ModelFile_RegionFromEdgeValidationError{
			field:  "Top",
			reason: "value must be inside range [0, 1)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetBottom(); val < 0 || val >= 1 {
		err := ModelFile_RegionFromEdgeValidationError{
			field:  "Bottom",
			reason: "value must be inside range [0, 1)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ModelFile_RegionFromEdgeMultiError(errors)
	}

	return nil
}

// ModelFile_RegionFromEdgeMultiError is an error wrapping multiple validation
// errors returned by ModelFile_RegionFromEdge.ValidateAll() if the designated
// constraints aren't met.
type ModelFile_RegionFromEdgeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelFile_RegionFromEdgeMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelFile_RegionFromEdgeMultiError) AllErrors() []error { return m }

// ModelFile_RegionFromEdgeValidationError is the validation error returned by
// ModelFile_RegionFromEdge.Validate if the designated constraints aren't met.
type ModelFile_RegionFromEdgeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelFile_RegionFromEdgeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModelFile_RegionFromEdgeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModelFile_RegionFromEdgeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModelFile_RegionFromEdgeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModelFile_RegionFromEdgeValidationError) ErrorName() string {
	return "ModelFile_RegionFromEdgeValidationError"
}

// Error satisfies the builtin error interface
func (e ModelFile_RegionFromEdgeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModelFile_RegionFromEdge.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelFile_RegionFromEdgeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelFile_RegionFromEdgeValidationError{}

// Validate checks the field values on ModelFile_InputFormatInformation with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ModelFile_InputFormatInformation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModelFile_InputFormatInformation with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ModelFile_InputFormatInformationMultiError, or nil if none found.
func (m *ModelFile_InputFormatInformation) ValidateAll() error {
	return m.validate(true)
}

func (m *ModelFile_InputFormatInformation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetInputs()) < 1 {
		err := ModelFile_InputFormatInformationValidationError{
			field:  "Inputs",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetInputs() {
		_, _ = idx, item

		if item == nil {
			err := ModelFile_InputFormatInformationValidationError{
				field:  fmt.Sprintf("Inputs[%v]", idx),
				reason: "value is required",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ModelFile_InputFormatInformationValidationError{
						field:  fmt.Sprintf("Inputs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ModelFile_InputFormatInformationValidationError{
						field:  fmt.Sprintf("Inputs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ModelFile_InputFormatInformationValidationError{
					field:  fmt.Sprintf("Inputs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ModelFile_InputFormatInformationMultiError(errors)
	}

	return nil
}

// ModelFile_InputFormatInformationMultiError is an error wrapping multiple
// validation errors returned by
// ModelFile_InputFormatInformation.ValidateAll() if the designated
// constraints aren't met.
type ModelFile_InputFormatInformationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelFile_InputFormatInformationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelFile_InputFormatInformationMultiError) AllErrors() []error { return m }

// ModelFile_InputFormatInformationValidationError is the validation error
// returned by ModelFile_InputFormatInformation.Validate if the designated
// constraints aren't met.
type ModelFile_InputFormatInformationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelFile_InputFormatInformationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModelFile_InputFormatInformationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModelFile_InputFormatInformationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModelFile_InputFormatInformationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModelFile_InputFormatInformationValidationError) ErrorName() string {
	return "ModelFile_InputFormatInformationValidationError"
}

// Error satisfies the builtin error interface
func (e ModelFile_InputFormatInformationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModelFile_InputFormatInformation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelFile_InputFormatInformationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelFile_InputFormatInformationValidationError{}

// Validate checks the field values on ModelFile_OutputDecodingInformation with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ModelFile_OutputDecodingInformation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModelFile_OutputDecodingInformation
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ModelFile_OutputDecodingInformationMultiError, or nil if none found.
func (m *ModelFile_OutputDecodingInformation) ValidateAll() error {
	return m.validate(true)
}

func (m *ModelFile_OutputDecodingInformation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DecodingType

	if len(m.GetOutputNames()) < 1 {
		err := ModelFile_OutputDecodingInformationValidationError{
			field:  "OutputNames",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.OcrDecodingInformation != nil {

		if all {
			switch v := interface{}(m.GetOcrDecodingInformation()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ModelFile_OutputDecodingInformationValidationError{
						field:  "OcrDecodingInformation",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ModelFile_OutputDecodingInformationValidationError{
						field:  "OcrDecodingInformation",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetOcrDecodingInformation()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ModelFile_OutputDecodingInformationValidationError{
					field:  "OcrDecodingInformation",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ModelFile_OutputDecodingInformationMultiError(errors)
	}

	return nil
}

// ModelFile_OutputDecodingInformationMultiError is an error wrapping multiple
// validation errors returned by
// ModelFile_OutputDecodingInformation.ValidateAll() if the designated
// constraints aren't met.
type ModelFile_OutputDecodingInformationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelFile_OutputDecodingInformationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelFile_OutputDecodingInformationMultiError) AllErrors() []error { return m }

// ModelFile_OutputDecodingInformationValidationError is the validation error
// returned by ModelFile_OutputDecodingInformation.Validate if the designated
// constraints aren't met.
type ModelFile_OutputDecodingInformationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelFile_OutputDecodingInformationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModelFile_OutputDecodingInformationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModelFile_OutputDecodingInformationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModelFile_OutputDecodingInformationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModelFile_OutputDecodingInformationValidationError) ErrorName() string {
	return "ModelFile_OutputDecodingInformationValidationError"
}

// Error satisfies the builtin error interface
func (e ModelFile_OutputDecodingInformationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModelFile_OutputDecodingInformation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelFile_OutputDecodingInformationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelFile_OutputDecodingInformationValidationError{}

// Validate checks the field values on ModelFile_FileInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ModelFile_FileInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModelFile_FileInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ModelFile_FileInfoMultiError, or nil if none found.
func (m *ModelFile_FileInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *ModelFile_FileInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for NetworkName

	if err := m._validateUuid(m.GetNetworkId()); err != nil {
		err = ModelFile_FileInfoValidationError{
			field:  "NetworkId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetNetworkExperimentId()); err != nil {
		err = ModelFile_FileInfoValidationError{
			field:  "NetworkExperimentId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetNetworkSnapshotId()); err != nil {
		err = ModelFile_FileInfoValidationError{
			field:  "NetworkSnapshotId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for NetworkType

	// no validation rules for NetworkFlavor

	if all {
		switch v := interface{}(m.GetNetworkVersion()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModelFile_FileInfoValidationError{
					field:  "NetworkVersion",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModelFile_FileInfoValidationError{
					field:  "NetworkVersion",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetNetworkVersion()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModelFile_FileInfoValidationError{
				field:  "NetworkVersion",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetRuntimeVersion()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModelFile_FileInfoValidationError{
					field:  "RuntimeVersion",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModelFile_FileInfoValidationError{
					field:  "RuntimeVersion",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRuntimeVersion()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModelFile_FileInfoValidationError{
				field:  "RuntimeVersion",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Precision

	if all {
		switch v := interface{}(m.GetMinimumLibdenkflowVersion()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModelFile_FileInfoValidationError{
					field:  "MinimumLibdenkflowVersion",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModelFile_FileInfoValidationError{
					field:  "MinimumLibdenkflowVersion",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMinimumLibdenkflowVersion()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModelFile_FileInfoValidationError{
				field:  "MinimumLibdenkflowVersion",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for NetworkSnapshotTimestamp

	if len(errors) > 0 {
		return ModelFile_FileInfoMultiError(errors)
	}

	return nil
}

func (m *ModelFile_FileInfo) _validateUuid(uuid string) error {
	if matched := _modelfile_v_2_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// ModelFile_FileInfoMultiError is an error wrapping multiple validation errors
// returned by ModelFile_FileInfo.ValidateAll() if the designated constraints
// aren't met.
type ModelFile_FileInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelFile_FileInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelFile_FileInfoMultiError) AllErrors() []error { return m }

// ModelFile_FileInfoValidationError is the validation error returned by
// ModelFile_FileInfo.Validate if the designated constraints aren't met.
type ModelFile_FileInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelFile_FileInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModelFile_FileInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModelFile_FileInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModelFile_FileInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModelFile_FileInfoValidationError) ErrorName() string {
	return "ModelFile_FileInfoValidationError"
}

// Error satisfies the builtin error interface
func (e ModelFile_FileInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModelFile_FileInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelFile_FileInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelFile_FileInfoValidationError{}

// Validate checks the field values on ModelFile_FileContent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ModelFile_FileContent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModelFile_FileContent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ModelFile_FileContentMultiError, or nil if none found.
func (m *ModelFile_FileContent) ValidateAll() error {
	return m.validate(true)
}

func (m *ModelFile_FileContent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	oneofFileTypePresent := false
	switch v := m.FileType.(type) {
	case *ModelFile_FileContent_DefaultModel_:
		if v == nil {
			err := ModelFile_FileContentValidationError{
				field:  "FileType",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofFileTypePresent = true

		if all {
			switch v := interface{}(m.GetDefaultModel()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ModelFile_FileContentValidationError{
						field:  "DefaultModel",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ModelFile_FileContentValidationError{
						field:  "DefaultModel",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDefaultModel()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ModelFile_FileContentValidationError{
					field:  "DefaultModel",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ModelFile_FileContent_TensorrtModel:
		if v == nil {
			err := ModelFile_FileContentValidationError{
				field:  "FileType",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofFileTypePresent = true

		if all {
			switch v := interface{}(m.GetTensorrtModel()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ModelFile_FileContentValidationError{
						field:  "TensorrtModel",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ModelFile_FileContentValidationError{
						field:  "TensorrtModel",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetTensorrtModel()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ModelFile_FileContentValidationError{
					field:  "TensorrtModel",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}
	if !oneofFileTypePresent {
		err := ModelFile_FileContentValidationError{
			field:  "FileType",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ModelFile_FileContentMultiError(errors)
	}

	return nil
}

// ModelFile_FileContentMultiError is an error wrapping multiple validation
// errors returned by ModelFile_FileContent.ValidateAll() if the designated
// constraints aren't met.
type ModelFile_FileContentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelFile_FileContentMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelFile_FileContentMultiError) AllErrors() []error { return m }

// ModelFile_FileContentValidationError is the validation error returned by
// ModelFile_FileContent.Validate if the designated constraints aren't met.
type ModelFile_FileContentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelFile_FileContentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModelFile_FileContentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModelFile_FileContentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModelFile_FileContentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModelFile_FileContentValidationError) ErrorName() string {
	return "ModelFile_FileContentValidationError"
}

// Error satisfies the builtin error interface
func (e ModelFile_FileContentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModelFile_FileContent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelFile_FileContentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelFile_FileContentValidationError{}

// Validate checks the field values on ModelFile_Content_KeySlot with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ModelFile_Content_KeySlot) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModelFile_Content_KeySlot with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ModelFile_Content_KeySlotMultiError, or nil if none found.
func (m *ModelFile_Content_KeySlot) ValidateAll() error {
	return m.validate(true)
}

func (m *ModelFile_Content_KeySlot) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for WrappedKey

	// no validation rules for WrappingMethod

	if len(errors) > 0 {
		return ModelFile_Content_KeySlotMultiError(errors)
	}

	return nil
}

// ModelFile_Content_KeySlotMultiError is an error wrapping multiple validation
// errors returned by ModelFile_Content_KeySlot.ValidateAll() if the
// designated constraints aren't met.
type ModelFile_Content_KeySlotMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelFile_Content_KeySlotMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelFile_Content_KeySlotMultiError) AllErrors() []error { return m }

// ModelFile_Content_KeySlotValidationError is the validation error returned by
// ModelFile_Content_KeySlot.Validate if the designated constraints aren't met.
type ModelFile_Content_KeySlotValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelFile_Content_KeySlotValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModelFile_Content_KeySlotValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModelFile_Content_KeySlotValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModelFile_Content_KeySlotValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModelFile_Content_KeySlotValidationError) ErrorName() string {
	return "ModelFile_Content_KeySlotValidationError"
}

// Error satisfies the builtin error interface
func (e ModelFile_Content_KeySlotValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModelFile_Content_KeySlot.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelFile_Content_KeySlotValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelFile_Content_KeySlotValidationError{}

// Validate checks the field values on ModelFile_InputFormatInformation_Input
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *ModelFile_InputFormatInformation_Input) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ModelFile_InputFormatInformation_Input with the rules defined in the proto
// definition for this message. If any rules are violated, the result is a
// list of violation errors wrapped in
// ModelFile_InputFormatInformation_InputMultiError, or nil if none found.
func (m *ModelFile_InputFormatInformation_Input) ValidateAll() error {
	return m.validate(true)
}

func (m *ModelFile_InputFormatInformation_Input) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for InputName

	switch v := m.FormatInformation.(type) {
	case *ModelFile_InputFormatInformation_Input_ImageFormat:
		if v == nil {
			err := ModelFile_InputFormatInformation_InputValidationError{
				field:  "FormatInformation",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetImageFormat()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ModelFile_InputFormatInformation_InputValidationError{
						field:  "ImageFormat",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ModelFile_InputFormatInformation_InputValidationError{
						field:  "ImageFormat",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetImageFormat()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ModelFile_InputFormatInformation_InputValidationError{
					field:  "ImageFormat",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return ModelFile_InputFormatInformation_InputMultiError(errors)
	}

	return nil
}

// ModelFile_InputFormatInformation_InputMultiError is an error wrapping
// multiple validation errors returned by
// ModelFile_InputFormatInformation_Input.ValidateAll() if the designated
// constraints aren't met.
type ModelFile_InputFormatInformation_InputMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelFile_InputFormatInformation_InputMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelFile_InputFormatInformation_InputMultiError) AllErrors() []error { return m }

// ModelFile_InputFormatInformation_InputValidationError is the validation
// error returned by ModelFile_InputFormatInformation_Input.Validate if the
// designated constraints aren't met.
type ModelFile_InputFormatInformation_InputValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelFile_InputFormatInformation_InputValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModelFile_InputFormatInformation_InputValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModelFile_InputFormatInformation_InputValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModelFile_InputFormatInformation_InputValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModelFile_InputFormatInformation_InputValidationError) ErrorName() string {
	return "ModelFile_InputFormatInformation_InputValidationError"
}

// Error satisfies the builtin error interface
func (e ModelFile_InputFormatInformation_InputValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModelFile_InputFormatInformation_Input.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelFile_InputFormatInformation_InputValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelFile_InputFormatInformation_InputValidationError{}

// Validate checks the field values on
// ModelFile_InputFormatInformation_Input_ImageInputFormat with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ModelFile_InputFormatInformation_Input_ImageInputFormat) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ModelFile_InputFormatInformation_Input_ImageInputFormat with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ModelFile_InputFormatInformation_Input_ImageInputFormatMultiError, or nil
// if none found.
func (m *ModelFile_InputFormatInformation_Input_ImageInputFormat) ValidateAll() error {
	return m.validate(true)
}

func (m *ModelFile_InputFormatInformation_Input_ImageInputFormat) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRegionOfInterest()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError{
					field:  "RegionOfInterest",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError{
					field:  "RegionOfInterest",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRegionOfInterest()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError{
				field:  "RegionOfInterest",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	switch v := m.ImageSizeRequirements.(type) {
	case *ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSize:
		if v == nil {
			err := ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError{
				field:  "ImageSizeRequirements",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetExactImageSize()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError{
						field:  "ExactImageSize",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError{
						field:  "ExactImageSize",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetExactImageSize()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError{
					field:  "ExactImageSize",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSize:
		if v == nil {
			err := ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError{
				field:  "ImageSizeRequirements",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetDivisibleImageSize()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError{
						field:  "DivisibleImageSize",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError{
						field:  "DivisibleImageSize",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDivisibleImageSize()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError{
					field:  "DivisibleImageSize",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return ModelFile_InputFormatInformation_Input_ImageInputFormatMultiError(errors)
	}

	return nil
}

// ModelFile_InputFormatInformation_Input_ImageInputFormatMultiError is an
// error wrapping multiple validation errors returned by
// ModelFile_InputFormatInformation_Input_ImageInputFormat.ValidateAll() if
// the designated constraints aren't met.
type ModelFile_InputFormatInformation_Input_ImageInputFormatMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelFile_InputFormatInformation_Input_ImageInputFormatMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelFile_InputFormatInformation_Input_ImageInputFormatMultiError) AllErrors() []error {
	return m
}

// ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError is
// the validation error returned by
// ModelFile_InputFormatInformation_Input_ImageInputFormat.Validate if the
// designated constraints aren't met.
type ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError) Field() string {
	return e.field
}

// Reason function returns reason value.
func (e ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError) Reason() string {
	return e.reason
}

// Cause function returns cause value.
func (e ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError) Cause() error {
	return e.cause
}

// Key function returns key value.
func (e ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError) Key() bool {
	return e.key
}

// ErrorName returns error name.
func (e ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError) ErrorName() string {
	return "ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError"
}

// Error satisfies the builtin error interface
func (e ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModelFile_InputFormatInformation_Input_ImageInputFormat.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelFile_InputFormatInformation_Input_ImageInputFormatValidationError{}

// Validate checks the field values on
// ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirement
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirement) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirement
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirementMultiError,
// or nil if none found.
func (m *ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirement) ValidateAll() error {
	return m.validate(true)
}

func (m *ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirement) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetImageSize()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirementValidationError{
					field:  "ImageSize",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirementValidationError{
					field:  "ImageSize",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetImageSize()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirementValidationError{
				field:  "ImageSize",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirementMultiError(errors)
	}

	return nil
}

// ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirementMultiError
// is an error wrapping multiple validation errors returned by
// ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirement.ValidateAll()
// if the designated constraints aren't met.
type ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirementMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirementMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirementMultiError) AllErrors() []error {
	return m
}

// ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirementValidationError
// is the validation error returned by
// ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirement.Validate
// if the designated constraints aren't met.
type ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirementValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirementValidationError) Field() string {
	return e.field
}

// Reason function returns reason value.
func (e ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirementValidationError) Reason() string {
	return e.reason
}

// Cause function returns cause value.
func (e ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirementValidationError) Cause() error {
	return e.cause
}

// Key function returns key value.
func (e ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirementValidationError) Key() bool {
	return e.key
}

// ErrorName returns error name.
func (e ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirementValidationError) ErrorName() string {
	return "ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirementValidationError"
}

// Error satisfies the builtin error interface
func (e ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirementValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirement.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirementValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelFile_InputFormatInformation_Input_ImageInputFormat_ExactImageSizeRequirementValidationError{}

// Validate checks the field values on
// ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirement
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirement) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirement
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementMultiError,
// or nil if none found.
func (m *ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirement) ValidateAll() error {
	return m.validate(true)
}

func (m *ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirement) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetImageSizeDivisors()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementValidationError{
					field:  "ImageSizeDivisors",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementValidationError{
					field:  "ImageSizeDivisors",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetImageSizeDivisors()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementValidationError{
				field:  "ImageSizeDivisors",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetMinimumImageSize()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementValidationError{
					field:  "MinimumImageSize",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementValidationError{
					field:  "MinimumImageSize",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMinimumImageSize()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementValidationError{
				field:  "MinimumImageSize",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSuggestedImageSize()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementValidationError{
					field:  "SuggestedImageSize",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementValidationError{
					field:  "SuggestedImageSize",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSuggestedImageSize()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementValidationError{
				field:  "SuggestedImageSize",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementMultiError(errors)
	}

	return nil
}

// ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementMultiError
// is an error wrapping multiple validation errors returned by
// ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirement.ValidateAll()
// if the designated constraints aren't met.
type ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementMultiError) AllErrors() []error {
	return m
}

// ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementValidationError
// is the validation error returned by
// ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirement.Validate
// if the designated constraints aren't met.
type ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementValidationError) Field() string {
	return e.field
}

// Reason function returns reason value.
func (e ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementValidationError) Reason() string {
	return e.reason
}

// Cause function returns cause value.
func (e ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementValidationError) Cause() error {
	return e.cause
}

// Key function returns key value.
func (e ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementValidationError) Key() bool {
	return e.key
}

// ErrorName returns error name.
func (e ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementValidationError) ErrorName() string {
	return "ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementValidationError"
}

// Error satisfies the builtin error interface
func (e ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirement.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelFile_InputFormatInformation_Input_ImageInputFormat_DivisibleImageSizeRequirementValidationError{}

// Validate checks the field values on
// ModelFile_OutputDecodingInformation_OcrDecodingInformation with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ModelFile_OutputDecodingInformation_OcrDecodingInformation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ModelFile_OutputDecodingInformation_OcrDecodingInformation with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ModelFile_OutputDecodingInformation_OcrDecodingInformationMultiError, or
// nil if none found.
func (m *ModelFile_OutputDecodingInformation_OcrDecodingInformation) ValidateAll() error {
	return m.validate(true)
}

func (m *ModelFile_OutputDecodingInformation_OcrDecodingInformation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Charset

	for idx, item := range m.GetFormatRestrictions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ModelFile_OutputDecodingInformation_OcrDecodingInformationValidationError{
						field:  fmt.Sprintf("FormatRestrictions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ModelFile_OutputDecodingInformation_OcrDecodingInformationValidationError{
						field:  fmt.Sprintf("FormatRestrictions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ModelFile_OutputDecodingInformation_OcrDecodingInformationValidationError{
					field:  fmt.Sprintf("FormatRestrictions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ModelFile_OutputDecodingInformation_OcrDecodingInformationMultiError(errors)
	}

	return nil
}

// ModelFile_OutputDecodingInformation_OcrDecodingInformationMultiError is an
// error wrapping multiple validation errors returned by
// ModelFile_OutputDecodingInformation_OcrDecodingInformation.ValidateAll() if
// the designated constraints aren't met.
type ModelFile_OutputDecodingInformation_OcrDecodingInformationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelFile_OutputDecodingInformation_OcrDecodingInformationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelFile_OutputDecodingInformation_OcrDecodingInformationMultiError) AllErrors() []error {
	return m
}

// ModelFile_OutputDecodingInformation_OcrDecodingInformationValidationError is
// the validation error returned by
// ModelFile_OutputDecodingInformation_OcrDecodingInformation.Validate if the
// designated constraints aren't met.
type ModelFile_OutputDecodingInformation_OcrDecodingInformationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelFile_OutputDecodingInformation_OcrDecodingInformationValidationError) Field() string {
	return e.field
}

// Reason function returns reason value.
func (e ModelFile_OutputDecodingInformation_OcrDecodingInformationValidationError) Reason() string {
	return e.reason
}

// Cause function returns cause value.
func (e ModelFile_OutputDecodingInformation_OcrDecodingInformationValidationError) Cause() error {
	return e.cause
}

// Key function returns key value.
func (e ModelFile_OutputDecodingInformation_OcrDecodingInformationValidationError) Key() bool {
	return e.key
}

// ErrorName returns error name.
func (e ModelFile_OutputDecodingInformation_OcrDecodingInformationValidationError) ErrorName() string {
	return "ModelFile_OutputDecodingInformation_OcrDecodingInformationValidationError"
}

// Error satisfies the builtin error interface
func (e ModelFile_OutputDecodingInformation_OcrDecodingInformationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModelFile_OutputDecodingInformation_OcrDecodingInformation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelFile_OutputDecodingInformation_OcrDecodingInformationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelFile_OutputDecodingInformation_OcrDecodingInformationValidationError{}

// Validate checks the field values on
// ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlock
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlock) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlock
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlockMultiError,
// or nil if none found.
func (m *ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlock) ValidateAll() error {
	return m.validate(true)
}

func (m *ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlock) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for NumberOfCharacters

	if len(errors) > 0 {
		return ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlockMultiError(errors)
	}

	return nil
}

// ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlockMultiError
// is an error wrapping multiple validation errors returned by
// ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlock.ValidateAll()
// if the designated constraints aren't met.
type ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlockMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlockMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlockMultiError) AllErrors() []error {
	return m
}

// ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlockValidationError
// is the validation error returned by
// ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlock.Validate
// if the designated constraints aren't met.
type ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlockValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlockValidationError) Field() string {
	return e.field
}

// Reason function returns reason value.
func (e ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlockValidationError) Reason() string {
	return e.reason
}

// Cause function returns cause value.
func (e ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlockValidationError) Cause() error {
	return e.cause
}

// Key function returns key value.
func (e ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlockValidationError) Key() bool {
	return e.key
}

// ErrorName returns error name.
func (e ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlockValidationError) ErrorName() string {
	return "ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlockValidationError"
}

// Error satisfies the builtin error interface
func (e ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlockValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlock.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlockValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelFile_OutputDecodingInformation_OcrDecodingInformation_FormatRestrictionBlockValidationError{}

// Validate checks the field values on ModelFile_FileContent_DefaultModel with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ModelFile_FileContent_DefaultModel) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModelFile_FileContent_DefaultModel
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ModelFile_FileContent_DefaultModelMultiError, or nil if none found.
func (m *ModelFile_FileContent_DefaultModel) ValidateAll() error {
	return m.validate(true)
}

func (m *ModelFile_FileContent_DefaultModel) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetModelData() == nil {
		err := ModelFile_FileContent_DefaultModelValidationError{
			field:  "ModelData",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetModelData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModelFile_FileContent_DefaultModelValidationError{
					field:  "ModelData",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModelFile_FileContent_DefaultModelValidationError{
					field:  "ModelData",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetModelData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModelFile_FileContent_DefaultModelValidationError{
				field:  "ModelData",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ModelFile_FileContent_DefaultModelMultiError(errors)
	}

	return nil
}

// ModelFile_FileContent_DefaultModelMultiError is an error wrapping multiple
// validation errors returned by
// ModelFile_FileContent_DefaultModel.ValidateAll() if the designated
// constraints aren't met.
type ModelFile_FileContent_DefaultModelMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelFile_FileContent_DefaultModelMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelFile_FileContent_DefaultModelMultiError) AllErrors() []error { return m }

// ModelFile_FileContent_DefaultModelValidationError is the validation error
// returned by ModelFile_FileContent_DefaultModel.Validate if the designated
// constraints aren't met.
type ModelFile_FileContent_DefaultModelValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelFile_FileContent_DefaultModelValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModelFile_FileContent_DefaultModelValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModelFile_FileContent_DefaultModelValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModelFile_FileContent_DefaultModelValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModelFile_FileContent_DefaultModelValidationError) ErrorName() string {
	return "ModelFile_FileContent_DefaultModelValidationError"
}

// Error satisfies the builtin error interface
func (e ModelFile_FileContent_DefaultModelValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModelFile_FileContent_DefaultModel.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelFile_FileContent_DefaultModelValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelFile_FileContent_DefaultModelValidationError{}

// Validate checks the field values on ModelFile_FileContent_TensorRTModel with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ModelFile_FileContent_TensorRTModel) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModelFile_FileContent_TensorRTModel
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ModelFile_FileContent_TensorRTModelMultiError, or nil if none found.
func (m *ModelFile_FileContent_TensorRTModel) ValidateAll() error {
	return m.validate(true)
}

func (m *ModelFile_FileContent_TensorRTModel) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetModelData() == nil {
		err := ModelFile_FileContent_TensorRTModelValidationError{
			field:  "ModelData",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetModelData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModelFile_FileContent_TensorRTModelValidationError{
					field:  "ModelData",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModelFile_FileContent_TensorRTModelValidationError{
					field:  "ModelData",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetModelData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModelFile_FileContent_TensorRTModelValidationError{
				field:  "ModelData",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetCalibrationCache() == nil {
		err := ModelFile_FileContent_TensorRTModelValidationError{
			field:  "CalibrationCache",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetCalibrationCache()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModelFile_FileContent_TensorRTModelValidationError{
					field:  "CalibrationCache",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModelFile_FileContent_TensorRTModelValidationError{
					field:  "CalibrationCache",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCalibrationCache()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModelFile_FileContent_TensorRTModelValidationError{
				field:  "CalibrationCache",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetCalibrationFlatbuffers() == nil {
		err := ModelFile_FileContent_TensorRTModelValidationError{
			field:  "CalibrationFlatbuffers",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetCalibrationFlatbuffers()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModelFile_FileContent_TensorRTModelValidationError{
					field:  "CalibrationFlatbuffers",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModelFile_FileContent_TensorRTModelValidationError{
					field:  "CalibrationFlatbuffers",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCalibrationFlatbuffers()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModelFile_FileContent_TensorRTModelValidationError{
				field:  "CalibrationFlatbuffers",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ModelFile_FileContent_TensorRTModelMultiError(errors)
	}

	return nil
}

// ModelFile_FileContent_TensorRTModelMultiError is an error wrapping multiple
// validation errors returned by
// ModelFile_FileContent_TensorRTModel.ValidateAll() if the designated
// constraints aren't met.
type ModelFile_FileContent_TensorRTModelMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelFile_FileContent_TensorRTModelMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelFile_FileContent_TensorRTModelMultiError) AllErrors() []error { return m }

// ModelFile_FileContent_TensorRTModelValidationError is the validation error
// returned by ModelFile_FileContent_TensorRTModel.Validate if the designated
// constraints aren't met.
type ModelFile_FileContent_TensorRTModelValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelFile_FileContent_TensorRTModelValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModelFile_FileContent_TensorRTModelValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModelFile_FileContent_TensorRTModelValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModelFile_FileContent_TensorRTModelValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModelFile_FileContent_TensorRTModelValidationError) ErrorName() string {
	return "ModelFile_FileContent_TensorRTModelValidationError"
}

// Error satisfies the builtin error interface
func (e ModelFile_FileContent_TensorRTModelValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModelFile_FileContent_TensorRTModel.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelFile_FileContent_TensorRTModelValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelFile_FileContent_TensorRTModelValidationError{}
