// This file should only ever be modified in a backwards compatible way.
// If unsure, consult https://protobuf.dev/programming-guides/proto3/

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: file_metadata.proto

package file_meta

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileType int32

const (
	FileType_FT_UNDEFINED FileType = 0
	FileType_FT_DENKMODEL FileType = 1
	FileType_FT_DENKFLOW  FileType = 2
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "FT_UNDEFINED",
		1: "FT_DENKMODEL",
		2: "FT_DENKFLOW",
	}
	FileType_value = map[string]int32{
		"FT_UNDEFINED": 0,
		"FT_DENKMODEL": 1,
		"FT_DENKFLOW":  2,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_file_meta_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_file_meta_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_file_meta_proto_rawDescGZIP(), []int{0}
}

type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	Patch         uint32                 `protobuf:"varint,3,opt,name=patch,proto3" json:"patch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_file_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_file_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_file_meta_proto_rawDescGZIP(), []int{0}
}

func (x *Version) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *Version) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *Version) GetPatch() uint32 {
	if x != nil {
		return x.Patch
	}
	return 0
}

type FileMeta struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	FileType                  FileType               `protobuf:"varint,1,opt,name=file_type,json=fileType,proto3,enum=file_meta.FileType" json:"file_type,omitempty"`
	CreatedAt                 int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DenkprotoVersion          *Version               `protobuf:"bytes,3,opt,name=denkproto_version,json=denkprotoVersion,proto3" json:"denkproto_version,omitempty"`                              // DENKproto version that the file has been created with
	MinimumLibdenkflowVersion *Version               `protobuf:"bytes,4,opt,name=minimum_libdenkflow_version,json=minimumLibdenkflowVersion,proto3" json:"minimum_libdenkflow_version,omitempty"` // Minimum version required to properly parse the file
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *FileMeta) Reset() {
	*x = FileMeta{}
	mi := &file_file_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMeta) ProtoMessage() {}

func (x *FileMeta) ProtoReflect() protoreflect.Message {
	mi := &file_file_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMeta.ProtoReflect.Descriptor instead.
func (*FileMeta) Descriptor() ([]byte, []int) {
	return file_file_meta_proto_rawDescGZIP(), []int{1}
}

func (x *FileMeta) GetFileType() FileType {
	if x != nil {
		return x.FileType
	}
	return FileType_FT_UNDEFINED
}

func (x *FileMeta) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FileMeta) GetDenkprotoVersion() *Version {
	if x != nil {
		return x.DenkprotoVersion
	}
	return nil
}

func (x *FileMeta) GetMinimumLibdenkflowVersion() *Version {
	if x != nil {
		return x.MinimumLibdenkflowVersion
	}
	return nil
}

type MinimalFileMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileMeta      *FileMeta              `protobuf:"bytes,1024,opt,name=file_meta,json=fileMeta,proto3" json:"file_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinimalFileMeta) Reset() {
	*x = MinimalFileMeta{}
	mi := &file_file_meta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinimalFileMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinimalFileMeta) ProtoMessage() {}

func (x *MinimalFileMeta) ProtoReflect() protoreflect.Message {
	mi := &file_file_meta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinimalFileMeta.ProtoReflect.Descriptor instead.
func (*MinimalFileMeta) Descriptor() ([]byte, []int) {
	return file_file_meta_proto_rawDescGZIP(), []int{2}
}

func (x *MinimalFileMeta) GetFileMeta() *FileMeta {
	if x != nil {
		return x.FileMeta
	}
	return nil
}

var File_file_meta_proto protoreflect.FileDescriptor

const file_file_meta_proto_rawDesc = "" +
	"\n" +
	"\x0ffile_metadata.proto\x12\tfile_meta\"K\n" +
	"\aVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\x12\x14\n" +
	"\x05patch\x18\x03 \x01(\rR\x05patch\"\xf0\x01\n" +
	"\bFileMeta\x120\n" +
	"\tfile_type\x18\x01 \x01(\x0e2\x13.file_meta.FileTypeR\bfileType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12?\n" +
	"\x11denkproto_version\x18\x03 \x01(\v2\x12.file_meta.VersionR\x10denkprotoVersion\x12R\n" +
	"\x1bminimum_libdenkflow_version\x18\x04 \x01(\v2\x12.file_meta.VersionR\x19minimumLibdenkflowVersion\"D\n" +
	"\x0fMinimalFileMeta\x121\n" +
	"\tfile_meta\x18\x80\b \x01(\v2\x13.file_meta.FileMetaR\bfileMeta*?\n" +
	"\bFileType\x12\x10\n" +
	"\fFT_UNDEFINED\x10\x00\x12\x10\n" +
	"\fFT_DENKMODEL\x10\x01\x12\x0f\n" +
	"\vFT_DENKFLOW\x10\x02BBZ*github.com/DENKweit/denkproto-go/file_meta\xaa\x02\x13DENK.Proto.FileMetab\x06proto3"

var (
	file_file_meta_proto_rawDescOnce sync.Once
	file_file_meta_proto_rawDescData []byte
)

func file_file_meta_proto_rawDescGZIP() []byte {
	file_file_meta_proto_rawDescOnce.Do(func() {
		file_file_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_meta_proto_rawDesc), len(file_file_meta_proto_rawDesc)))
	})
	return file_file_meta_proto_rawDescData
}

var file_file_meta_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_file_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_file_meta_proto_goTypes = []any{
	(FileType)(0),           // 0: file_meta.FileType
	(*Version)(nil),         // 1: file_meta.Version
	(*FileMeta)(nil),        // 2: file_meta.FileMeta
	(*MinimalFileMeta)(nil), // 3: file_meta.MinimalFileMeta
}
var file_file_meta_proto_depIdxs = []int32{
	0, // 0: file_meta.FileMeta.file_type:type_name -> file_meta.FileType
	1, // 1: file_meta.FileMeta.denkproto_version:type_name -> file_meta.Version
	1, // 2: file_meta.FileMeta.minimum_libdenkflow_version:type_name -> file_meta.Version
	2, // 3: file_meta.MinimalFileMeta.file_meta:type_name -> file_meta.FileMeta
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_file_meta_proto_init() }
func file_file_meta_proto_init() {
	if File_file_meta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_meta_proto_rawDesc), len(file_file_meta_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_meta_proto_goTypes,
		DependencyIndexes: file_file_meta_proto_depIdxs,
		EnumInfos:         file_file_meta_proto_enumTypes,
		MessageInfos:      file_file_meta_proto_msgTypes,
	}.Build()
	File_file_meta_proto = out.File
	file_file_meta_proto_goTypes = nil
	file_file_meta_proto_depIdxs = nil
}
