// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.26.0
// source: denkcache.proto

package denkcache

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectSource int32

const (
	ObjectSource_OBJECT_SOURCE_MEMORY    ObjectSource = 0
	ObjectSource_OBJECT_SOURCE_DISK      ObjectSource = 1
	ObjectSource_OBJECT_SOURCE_DENKCACHE ObjectSource = 2
	ObjectSource_OBJECT_SOURCE_AZURE     ObjectSource = 3
)

// Enum value maps for ObjectSource.
var (
	ObjectSource_name = map[int32]string{
		0: "OBJECT_SOURCE_MEMORY",
		1: "OBJECT_SOURCE_DISK",
		2: "OBJECT_SOURCE_DENKCACHE",
		3: "OBJECT_SOURCE_AZURE",
	}
	ObjectSource_value = map[string]int32{
		"OBJECT_SOURCE_MEMORY":    0,
		"OBJECT_SOURCE_DISK":      1,
		"OBJECT_SOURCE_DENKCACHE": 2,
		"OBJECT_SOURCE_AZURE":     3,
	}
)

func (x ObjectSource) Enum() *ObjectSource {
	p := new(ObjectSource)
	*p = x
	return p
}

func (x ObjectSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectSource) Descriptor() protoreflect.EnumDescriptor {
	return file_denkcache_proto_enumTypes[0].Descriptor()
}

func (ObjectSource) Type() protoreflect.EnumType {
	return &file_denkcache_proto_enumTypes[0]
}

func (x ObjectSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectSource.Descriptor instead.
func (ObjectSource) EnumDescriptor() ([]byte, []int) {
	return file_denkcache_proto_rawDescGZIP(), []int{0}
}

type CacheObjectPolicy int32

const (
	CacheObjectPolicy_MEMORY_ONLY     CacheObjectPolicy = 0
	CacheObjectPolicy_DISK_ONLY       CacheObjectPolicy = 1
	CacheObjectPolicy_MEMORY_AND_DISK CacheObjectPolicy = 2
)

// Enum value maps for CacheObjectPolicy.
var (
	CacheObjectPolicy_name = map[int32]string{
		0: "MEMORY_ONLY",
		1: "DISK_ONLY",
		2: "MEMORY_AND_DISK",
	}
	CacheObjectPolicy_value = map[string]int32{
		"MEMORY_ONLY":     0,
		"DISK_ONLY":       1,
		"MEMORY_AND_DISK": 2,
	}
)

func (x CacheObjectPolicy) Enum() *CacheObjectPolicy {
	p := new(CacheObjectPolicy)
	*p = x
	return p
}

func (x CacheObjectPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CacheObjectPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_denkcache_proto_enumTypes[1].Descriptor()
}

func (CacheObjectPolicy) Type() protoreflect.EnumType {
	return &file_denkcache_proto_enumTypes[1]
}

func (x CacheObjectPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CacheObjectPolicy.Descriptor instead.
func (CacheObjectPolicy) EnumDescriptor() ([]byte, []int) {
	return file_denkcache_proto_rawDescGZIP(), []int{1}
}

type ObjectExistsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerName string `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	BlobName      string `protobuf:"bytes,2,opt,name=blob_name,json=blobName,proto3" json:"blob_name,omitempty"`
}

func (x *ObjectExistsRequest) Reset() {
	*x = ObjectExistsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_denkcache_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectExistsRequest) ProtoMessage() {}

func (x *ObjectExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_denkcache_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectExistsRequest.ProtoReflect.Descriptor instead.
func (*ObjectExistsRequest) Descriptor() ([]byte, []int) {
	return file_denkcache_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectExistsRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ObjectExistsRequest) GetBlobName() string {
	if x != nil {
		return x.BlobName
	}
	return ""
}

type ObjectExistsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *ObjectExistsResponse) Reset() {
	*x = ObjectExistsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_denkcache_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectExistsResponse) ProtoMessage() {}

func (x *ObjectExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_denkcache_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectExistsResponse.ProtoReflect.Descriptor instead.
func (*ObjectExistsResponse) Descriptor() ([]byte, []int) {
	return file_denkcache_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type ObjectSourceMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source     ObjectSource `protobuf:"varint,1,opt,name=source,proto3,enum=denkcache.ObjectSource" json:"source,omitempty"`
	SourceInfo *string      `protobuf:"bytes,2,opt,name=source_info,json=sourceInfo,proto3,oneof" json:"source_info,omitempty"`
}

func (x *ObjectSourceMessage) Reset() {
	*x = ObjectSourceMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_denkcache_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectSourceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectSourceMessage) ProtoMessage() {}

func (x *ObjectSourceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_denkcache_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectSourceMessage.ProtoReflect.Descriptor instead.
func (*ObjectSourceMessage) Descriptor() ([]byte, []int) {
	return file_denkcache_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectSourceMessage) GetSource() ObjectSource {
	if x != nil {
		return x.Source
	}
	return ObjectSource_OBJECT_SOURCE_MEMORY
}

func (x *ObjectSourceMessage) GetSourceInfo() string {
	if x != nil && x.SourceInfo != nil {
		return *x.SourceInfo
	}
	return ""
}

type GetObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerName string `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	BlobName      string `protobuf:"bytes,2,opt,name=blob_name,json=blobName,proto3" json:"blob_name,omitempty"`
}

func (x *GetObjectRequest) Reset() {
	*x = GetObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_denkcache_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectRequest) ProtoMessage() {}

func (x *GetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_denkcache_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectRequest.ProtoReflect.Descriptor instead.
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return file_denkcache_proto_rawDescGZIP(), []int{3}
}

func (x *GetObjectRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *GetObjectRequest) GetBlobName() string {
	if x != nil {
		return x.BlobName
	}
	return ""
}

type GetObjectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object []byte               `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Source *ObjectSourceMessage `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *GetObjectResponse) Reset() {
	*x = GetObjectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_denkcache_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectResponse) ProtoMessage() {}

func (x *GetObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_denkcache_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectResponse.ProtoReflect.Descriptor instead.
func (*GetObjectResponse) Descriptor() ([]byte, []int) {
	return file_denkcache_proto_rawDescGZIP(), []int{4}
}

func (x *GetObjectResponse) GetObject() []byte {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *GetObjectResponse) GetSource() *ObjectSourceMessage {
	if x != nil {
		return x.Source
	}
	return nil
}

type CacheObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerName string             `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	BlobName      string             `protobuf:"bytes,2,opt,name=blob_name,json=blobName,proto3" json:"blob_name,omitempty"`
	Object        []byte             `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	CachePolicy   *CacheObjectPolicy `protobuf:"varint,4,opt,name=cache_policy,json=cachePolicy,proto3,enum=denkcache.CacheObjectPolicy,oneof" json:"cache_policy,omitempty"`
}

func (x *CacheObjectRequest) Reset() {
	*x = CacheObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_denkcache_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheObjectRequest) ProtoMessage() {}

func (x *CacheObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_denkcache_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheObjectRequest.ProtoReflect.Descriptor instead.
func (*CacheObjectRequest) Descriptor() ([]byte, []int) {
	return file_denkcache_proto_rawDescGZIP(), []int{5}
}

func (x *CacheObjectRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *CacheObjectRequest) GetBlobName() string {
	if x != nil {
		return x.BlobName
	}
	return ""
}

func (x *CacheObjectRequest) GetObject() []byte {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *CacheObjectRequest) GetCachePolicy() CacheObjectPolicy {
	if x != nil && x.CachePolicy != nil {
		return *x.CachePolicy
	}
	return CacheObjectPolicy_MEMORY_ONLY
}

type CacheObjectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CacheObjectResponse) Reset() {
	*x = CacheObjectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_denkcache_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheObjectResponse) ProtoMessage() {}

func (x *CacheObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_denkcache_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheObjectResponse.ProtoReflect.Descriptor instead.
func (*CacheObjectResponse) Descriptor() ([]byte, []int) {
	return file_denkcache_proto_rawDescGZIP(), []int{6}
}

type GetCachedObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerName string             `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	BlobName      string             `protobuf:"bytes,2,opt,name=blob_name,json=blobName,proto3" json:"blob_name,omitempty"`
	CachePolicy   *CacheObjectPolicy `protobuf:"varint,3,opt,name=cache_policy,json=cachePolicy,proto3,enum=denkcache.CacheObjectPolicy,oneof" json:"cache_policy,omitempty"`
}

func (x *GetCachedObjectRequest) Reset() {
	*x = GetCachedObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_denkcache_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCachedObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCachedObjectRequest) ProtoMessage() {}

func (x *GetCachedObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_denkcache_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCachedObjectRequest.ProtoReflect.Descriptor instead.
func (*GetCachedObjectRequest) Descriptor() ([]byte, []int) {
	return file_denkcache_proto_rawDescGZIP(), []int{7}
}

func (x *GetCachedObjectRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *GetCachedObjectRequest) GetBlobName() string {
	if x != nil {
		return x.BlobName
	}
	return ""
}

func (x *GetCachedObjectRequest) GetCachePolicy() CacheObjectPolicy {
	if x != nil && x.CachePolicy != nil {
		return *x.CachePolicy
	}
	return CacheObjectPolicy_MEMORY_ONLY
}

type GetCachedObjectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object []byte `protobuf:"bytes,1,opt,name=object,proto3,oneof" json:"object,omitempty"`
}

func (x *GetCachedObjectResponse) Reset() {
	*x = GetCachedObjectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_denkcache_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCachedObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCachedObjectResponse) ProtoMessage() {}

func (x *GetCachedObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_denkcache_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCachedObjectResponse.ProtoReflect.Descriptor instead.
func (*GetCachedObjectResponse) Descriptor() ([]byte, []int) {
	return file_denkcache_proto_rawDescGZIP(), []int{8}
}

func (x *GetCachedObjectResponse) GetObject() []byte {
	if x != nil {
		return x.Object
	}
	return nil
}

type HasObjectCachedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerName string `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	BlobName      string `protobuf:"bytes,2,opt,name=blob_name,json=blobName,proto3" json:"blob_name,omitempty"`
}

func (x *HasObjectCachedRequest) Reset() {
	*x = HasObjectCachedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_denkcache_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasObjectCachedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasObjectCachedRequest) ProtoMessage() {}

func (x *HasObjectCachedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_denkcache_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasObjectCachedRequest.ProtoReflect.Descriptor instead.
func (*HasObjectCachedRequest) Descriptor() ([]byte, []int) {
	return file_denkcache_proto_rawDescGZIP(), []int{9}
}

func (x *HasObjectCachedRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *HasObjectCachedRequest) GetBlobName() string {
	if x != nil {
		return x.BlobName
	}
	return ""
}

type HasObjectCachedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *HasObjectCachedResponse) Reset() {
	*x = HasObjectCachedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_denkcache_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasObjectCachedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasObjectCachedResponse) ProtoMessage() {}

func (x *HasObjectCachedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_denkcache_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasObjectCachedResponse.ProtoReflect.Descriptor instead.
func (*HasObjectCachedResponse) Descriptor() ([]byte, []int) {
	return file_denkcache_proto_rawDescGZIP(), []int{10}
}

func (x *HasObjectCachedResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type PingPongRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingPongRequest) Reset() {
	*x = PingPongRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_denkcache_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingPongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingPongRequest) ProtoMessage() {}

func (x *PingPongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_denkcache_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingPongRequest.ProtoReflect.Descriptor instead.
func (*PingPongRequest) Descriptor() ([]byte, []int) {
	return file_denkcache_proto_rawDescGZIP(), []int{11}
}

type PingPongResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingPongResponse) Reset() {
	*x = PingPongResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_denkcache_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingPongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingPongResponse) ProtoMessage() {}

func (x *PingPongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_denkcache_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingPongResponse.ProtoReflect.Descriptor instead.
func (*PingPongResponse) Descriptor() ([]byte, []int) {
	return file_denkcache_proto_rawDescGZIP(), []int{12}
}

type ChangeSettingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogLevel *string `protobuf:"bytes,1,opt,name=log_level,json=logLevel,proto3,oneof" json:"log_level,omitempty"`
}

func (x *ChangeSettingsRequest) Reset() {
	*x = ChangeSettingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_denkcache_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSettingsRequest) ProtoMessage() {}

func (x *ChangeSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_denkcache_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSettingsRequest.ProtoReflect.Descriptor instead.
func (*ChangeSettingsRequest) Descriptor() ([]byte, []int) {
	return file_denkcache_proto_rawDescGZIP(), []int{13}
}

func (x *ChangeSettingsRequest) GetLogLevel() string {
	if x != nil && x.LogLevel != nil {
		return *x.LogLevel
	}
	return ""
}

type ChangeSettingsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChangeSettingsResponse) Reset() {
	*x = ChangeSettingsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_denkcache_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSettingsResponse) ProtoMessage() {}

func (x *ChangeSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_denkcache_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSettingsResponse.ProtoReflect.Descriptor instead.
func (*ChangeSettingsResponse) Descriptor() ([]byte, []int) {
	return file_denkcache_proto_rawDescGZIP(), []int{14}
}

var File_denkcache_proto protoreflect.FileDescriptor

var file_denkcache_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x65, 0x6e, 0x6b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x64, 0x65, 0x6e, 0x6b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x22, 0x59, 0x0a, 0x13,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c,
	0x6f, 0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62,
	0x6c, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x14, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x22, 0x7c, 0x0a, 0x13, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2f,
	0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17,
	0x2e, 0x64, 0x65, 0x6e, 0x6b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12,
	0x24, 0x0a, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x56, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x63, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x36, 0x0a, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x65, 0x6e,
	0x6b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x22, 0xc7, 0x01, 0x0a, 0x12, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x44, 0x0a, 0x0c, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x64, 0x65,
	0x6e, 0x6b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x22, 0x15, 0x0a, 0x13,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0xb3, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25,
	0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x62, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x62, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x44, 0x0a, 0x0c, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x64, 0x65, 0x6e, 0x6b, 0x63,
	0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x22, 0x41, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x88, 0x01,
	0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x5c, 0x0a, 0x16,
	0x48, 0x61, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x62, 0x6c, 0x6f, 0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x62, 0x6c, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x31, 0x0a, 0x17, 0x48, 0x61,
	0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x22, 0x11, 0x0a,
	0x0f, 0x50, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x12, 0x0a, 0x10, 0x50, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x47, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a,
	0x09, 0x6c, 0x6f, 0x67, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x88, 0x01, 0x01, 0x42,
	0x0c, 0x0a, 0x0a, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x18, 0x0a,
	0x16, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x76, 0x0a, 0x0c, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x4f, 0x42, 0x4a, 0x45, 0x43,
	0x54, 0x5f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x4d, 0x45, 0x4d, 0x4f, 0x52, 0x59, 0x10,
	0x00, 0x12, 0x16, 0x0a, 0x12, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x53, 0x4f, 0x55, 0x52,
	0x43, 0x45, 0x5f, 0x44, 0x49, 0x53, 0x4b, 0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x4f, 0x42, 0x4a,
	0x45, 0x43, 0x54, 0x5f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x44, 0x45, 0x4e, 0x4b, 0x43,
	0x41, 0x43, 0x48, 0x45, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54,
	0x5f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x41, 0x5a, 0x55, 0x52, 0x45, 0x10, 0x03, 0x2a,
	0x48, 0x0a, 0x11, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x45, 0x4d, 0x4f, 0x52, 0x59, 0x5f, 0x4f,
	0x4e, 0x4c, 0x59, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x49, 0x53, 0x4b, 0x5f, 0x4f, 0x4e,
	0x4c, 0x59, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x45, 0x4d, 0x4f, 0x52, 0x59, 0x5f, 0x41,
	0x4e, 0x44, 0x5f, 0x44, 0x49, 0x53, 0x4b, 0x10, 0x02, 0x32, 0xc2, 0x04, 0x0a, 0x09, 0x44, 0x45,
	0x4e, 0x4b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x12, 0x55, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x20, 0x2e, 0x64, 0x65, 0x6e, 0x6b,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x64, 0x65,
	0x6e, 0x6b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43,
	0x0a, 0x08, 0x50, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x1a, 0x2e, 0x64, 0x65, 0x6e,
	0x6b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x64, 0x65, 0x6e, 0x6b, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x0f, 0x48, 0x61, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x12, 0x21, 0x2e, 0x64, 0x65, 0x6e, 0x6b, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x48, 0x61, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x64, 0x65, 0x6e, 0x6b,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x48, 0x61, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a,
	0x0c, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x1e, 0x2e,
	0x64, 0x65, 0x6e, 0x6b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x64, 0x65, 0x6e, 0x6b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46,
	0x0a, 0x09, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1b, 0x2e, 0x64, 0x65,
	0x6e, 0x6b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x64, 0x65, 0x6e, 0x6b, 0x63,
	0x61, 0x63, 0x68, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0b, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1d, 0x2e, 0x64, 0x65, 0x6e, 0x6b, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x64, 0x65, 0x6e, 0x6b, 0x63, 0x61, 0x63, 0x68, 0x65,
	0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x21, 0x2e, 0x64, 0x65, 0x6e, 0x6b, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x64, 0x65, 0x6e,
	0x6b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x64,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2f,
	0x5a, 0x16, 0x64, 0x65, 0x6e, 0x6b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x2f, 0x64,
	0x65, 0x6e, 0x6b, 0x63, 0x61, 0x63, 0x68, 0x65, 0xaa, 0x02, 0x14, 0x44, 0x45, 0x4e, 0x4b, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x45, 0x4e, 0x4b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_denkcache_proto_rawDescOnce sync.Once
	file_denkcache_proto_rawDescData = file_denkcache_proto_rawDesc
)

func file_denkcache_proto_rawDescGZIP() []byte {
	file_denkcache_proto_rawDescOnce.Do(func() {
		file_denkcache_proto_rawDescData = protoimpl.X.CompressGZIP(file_denkcache_proto_rawDescData)
	})
	return file_denkcache_proto_rawDescData
}

var file_denkcache_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_denkcache_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_denkcache_proto_goTypes = []interface{}{
	(ObjectSource)(0),               // 0: denkcache.ObjectSource
	(CacheObjectPolicy)(0),          // 1: denkcache.CacheObjectPolicy
	(*ObjectExistsRequest)(nil),     // 2: denkcache.ObjectExistsRequest
	(*ObjectExistsResponse)(nil),    // 3: denkcache.ObjectExistsResponse
	(*ObjectSourceMessage)(nil),     // 4: denkcache.ObjectSourceMessage
	(*GetObjectRequest)(nil),        // 5: denkcache.GetObjectRequest
	(*GetObjectResponse)(nil),       // 6: denkcache.GetObjectResponse
	(*CacheObjectRequest)(nil),      // 7: denkcache.CacheObjectRequest
	(*CacheObjectResponse)(nil),     // 8: denkcache.CacheObjectResponse
	(*GetCachedObjectRequest)(nil),  // 9: denkcache.GetCachedObjectRequest
	(*GetCachedObjectResponse)(nil), // 10: denkcache.GetCachedObjectResponse
	(*HasObjectCachedRequest)(nil),  // 11: denkcache.HasObjectCachedRequest
	(*HasObjectCachedResponse)(nil), // 12: denkcache.HasObjectCachedResponse
	(*PingPongRequest)(nil),         // 13: denkcache.PingPongRequest
	(*PingPongResponse)(nil),        // 14: denkcache.PingPongResponse
	(*ChangeSettingsRequest)(nil),   // 15: denkcache.ChangeSettingsRequest
	(*ChangeSettingsResponse)(nil),  // 16: denkcache.ChangeSettingsResponse
}
var file_denkcache_proto_depIdxs = []int32{
	0,  // 0: denkcache.ObjectSourceMessage.source:type_name -> denkcache.ObjectSource
	4,  // 1: denkcache.GetObjectResponse.source:type_name -> denkcache.ObjectSourceMessage
	1,  // 2: denkcache.CacheObjectRequest.cache_policy:type_name -> denkcache.CacheObjectPolicy
	1,  // 3: denkcache.GetCachedObjectRequest.cache_policy:type_name -> denkcache.CacheObjectPolicy
	15, // 4: denkcache.DENKcache.ChangeSettings:input_type -> denkcache.ChangeSettingsRequest
	13, // 5: denkcache.DENKcache.PingPong:input_type -> denkcache.PingPongRequest
	11, // 6: denkcache.DENKcache.HasObjectCached:input_type -> denkcache.HasObjectCachedRequest
	2,  // 7: denkcache.DENKcache.ObjectExists:input_type -> denkcache.ObjectExistsRequest
	5,  // 8: denkcache.DENKcache.GetObject:input_type -> denkcache.GetObjectRequest
	7,  // 9: denkcache.DENKcache.CacheObject:input_type -> denkcache.CacheObjectRequest
	9,  // 10: denkcache.DENKcache.GetCachedObject:input_type -> denkcache.GetCachedObjectRequest
	16, // 11: denkcache.DENKcache.ChangeSettings:output_type -> denkcache.ChangeSettingsResponse
	14, // 12: denkcache.DENKcache.PingPong:output_type -> denkcache.PingPongResponse
	12, // 13: denkcache.DENKcache.HasObjectCached:output_type -> denkcache.HasObjectCachedResponse
	3,  // 14: denkcache.DENKcache.ObjectExists:output_type -> denkcache.ObjectExistsResponse
	6,  // 15: denkcache.DENKcache.GetObject:output_type -> denkcache.GetObjectResponse
	8,  // 16: denkcache.DENKcache.CacheObject:output_type -> denkcache.CacheObjectResponse
	10, // 17: denkcache.DENKcache.GetCachedObject:output_type -> denkcache.GetCachedObjectResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_denkcache_proto_init() }
func file_denkcache_proto_init() {
	if File_denkcache_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_denkcache_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectExistsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_denkcache_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectExistsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_denkcache_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectSourceMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_denkcache_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_denkcache_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetObjectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_denkcache_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CacheObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_denkcache_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CacheObjectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_denkcache_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCachedObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_denkcache_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCachedObjectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_denkcache_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasObjectCachedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_denkcache_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasObjectCachedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_denkcache_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingPongRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_denkcache_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingPongResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_denkcache_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeSettingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_denkcache_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeSettingsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_denkcache_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_denkcache_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_denkcache_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_denkcache_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_denkcache_proto_msgTypes[13].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_denkcache_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_denkcache_proto_goTypes,
		DependencyIndexes: file_denkcache_proto_depIdxs,
		EnumInfos:         file_denkcache_proto_enumTypes,
		MessageInfos:      file_denkcache_proto_msgTypes,
	}.Build()
	File_denkcache_proto = out.File
	file_denkcache_proto_rawDesc = nil
	file_denkcache_proto_goTypes = nil
	file_denkcache_proto_depIdxs = nil
}
