// Definition of Materialized Markup Structure
// Version 0.1

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: materialized_markup.proto

package materialized_markup

import (
	geometry "github.com/DENKweit/denkproto-go/geometry"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FocusAreaType int32

const (
	FocusAreaType_FOCUS_AREA_TYPE_UNSPECIFIED FocusAreaType = 0
	FocusAreaType_FOCUS_AREA_TYPE_NEGATIVE    FocusAreaType = 1
	FocusAreaType_FOCUS_AREA_TYPE_IGNORE      FocusAreaType = 2
	FocusAreaType_FOCUS_AREA_TYPE_ROI         FocusAreaType = 3
)

// Enum value maps for FocusAreaType.
var (
	FocusAreaType_name = map[int32]string{
		0: "FOCUS_AREA_TYPE_UNSPECIFIED",
		1: "FOCUS_AREA_TYPE_NEGATIVE",
		2: "FOCUS_AREA_TYPE_IGNORE",
		3: "FOCUS_AREA_TYPE_ROI",
	}
	FocusAreaType_value = map[string]int32{
		"FOCUS_AREA_TYPE_UNSPECIFIED": 0,
		"FOCUS_AREA_TYPE_NEGATIVE":    1,
		"FOCUS_AREA_TYPE_IGNORE":      2,
		"FOCUS_AREA_TYPE_ROI":         3,
	}
)

func (x FocusAreaType) Enum() *FocusAreaType {
	p := new(FocusAreaType)
	*p = x
	return p
}

func (x FocusAreaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FocusAreaType) Descriptor() protoreflect.EnumDescriptor {
	return file_materialized_markup_proto_enumTypes[0].Descriptor()
}

func (FocusAreaType) Type() protoreflect.EnumType {
	return &file_materialized_markup_proto_enumTypes[0]
}

func (x FocusAreaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FocusAreaType.Descriptor instead.
func (FocusAreaType) EnumDescriptor() ([]byte, []int) {
	return file_materialized_markup_proto_rawDescGZIP(), []int{0}
}

type ClassificationAnnotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LabelId       string                 `protobuf:"bytes,2,opt,name=label_id,json=labelId,proto3" json:"label_id,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassificationAnnotation) Reset() {
	*x = ClassificationAnnotation{}
	mi := &file_materialized_markup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassificationAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassificationAnnotation) ProtoMessage() {}

func (x *ClassificationAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_materialized_markup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassificationAnnotation.ProtoReflect.Descriptor instead.
func (*ClassificationAnnotation) Descriptor() ([]byte, []int) {
	return file_materialized_markup_proto_rawDescGZIP(), []int{0}
}

func (x *ClassificationAnnotation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClassificationAnnotation) GetLabelId() string {
	if x != nil {
		return x.LabelId
	}
	return ""
}

func (x *ClassificationAnnotation) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type InstanceSegmentationAnnotation struct {
	state                    protoimpl.MessageState             `protogen:"open.v1"`
	Id                       string                             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LabelId                  string                             `protobuf:"bytes,2,opt,name=label_id,json=labelId,proto3" json:"label_id,omitempty"`
	InstanceSegmentationMask *geometry.InstanceSegmentationMask `protobuf:"bytes,3,opt,name=instance_segmentation_mask,json=instanceSegmentationMask,proto3" json:"instance_segmentation_mask,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *InstanceSegmentationAnnotation) Reset() {
	*x = InstanceSegmentationAnnotation{}
	mi := &file_materialized_markup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceSegmentationAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceSegmentationAnnotation) ProtoMessage() {}

func (x *InstanceSegmentationAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_materialized_markup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceSegmentationAnnotation.ProtoReflect.Descriptor instead.
func (*InstanceSegmentationAnnotation) Descriptor() ([]byte, []int) {
	return file_materialized_markup_proto_rawDescGZIP(), []int{1}
}

func (x *InstanceSegmentationAnnotation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InstanceSegmentationAnnotation) GetLabelId() string {
	if x != nil {
		return x.LabelId
	}
	return ""
}

func (x *InstanceSegmentationAnnotation) GetInstanceSegmentationMask() *geometry.InstanceSegmentationMask {
	if x != nil {
		return x.InstanceSegmentationMask
	}
	return nil
}

type ObjectDetectionAnnotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LabelId       string                 `protobuf:"bytes,2,opt,name=label_id,json=labelId,proto3" json:"label_id,omitempty"`
	BoundingBox   *geometry.BoundingBox  `protobuf:"bytes,3,opt,name=bounding_box,json=boundingBox,proto3" json:"bounding_box,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectDetectionAnnotation) Reset() {
	*x = ObjectDetectionAnnotation{}
	mi := &file_materialized_markup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectDetectionAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectDetectionAnnotation) ProtoMessage() {}

func (x *ObjectDetectionAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_materialized_markup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectDetectionAnnotation.ProtoReflect.Descriptor instead.
func (*ObjectDetectionAnnotation) Descriptor() ([]byte, []int) {
	return file_materialized_markup_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectDetectionAnnotation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObjectDetectionAnnotation) GetLabelId() string {
	if x != nil {
		return x.LabelId
	}
	return ""
}

func (x *ObjectDetectionAnnotation) GetBoundingBox() *geometry.BoundingBox {
	if x != nil {
		return x.BoundingBox
	}
	return nil
}

type OcrAnnotation struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LabelId string                 `protobuf:"bytes,2,opt,name=label_id,json=labelId,proto3" json:"label_id,omitempty"`
	Text    string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// Types that are valid to be assigned to GeometryData:
	//
	//	*OcrAnnotation_BoundingBox
	//	*OcrAnnotation_Polygon
	GeometryData  isOcrAnnotation_GeometryData `protobuf_oneof:"geometry_data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OcrAnnotation) Reset() {
	*x = OcrAnnotation{}
	mi := &file_materialized_markup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OcrAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OcrAnnotation) ProtoMessage() {}

func (x *OcrAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_materialized_markup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OcrAnnotation.ProtoReflect.Descriptor instead.
func (*OcrAnnotation) Descriptor() ([]byte, []int) {
	return file_materialized_markup_proto_rawDescGZIP(), []int{3}
}

func (x *OcrAnnotation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OcrAnnotation) GetLabelId() string {
	if x != nil {
		return x.LabelId
	}
	return ""
}

func (x *OcrAnnotation) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OcrAnnotation) GetGeometryData() isOcrAnnotation_GeometryData {
	if x != nil {
		return x.GeometryData
	}
	return nil
}

func (x *OcrAnnotation) GetBoundingBox() *geometry.BoundingBox {
	if x != nil {
		if x, ok := x.GeometryData.(*OcrAnnotation_BoundingBox); ok {
			return x.BoundingBox
		}
	}
	return nil
}

func (x *OcrAnnotation) GetPolygon() *geometry.Polygon {
	if x != nil {
		if x, ok := x.GeometryData.(*OcrAnnotation_Polygon); ok {
			return x.Polygon
		}
	}
	return nil
}

type isOcrAnnotation_GeometryData interface {
	isOcrAnnotation_GeometryData()
}

type OcrAnnotation_BoundingBox struct {
	BoundingBox *geometry.BoundingBox `protobuf:"bytes,4,opt,name=bounding_box,json=boundingBox,proto3,oneof"`
}

type OcrAnnotation_Polygon struct {
	Polygon *geometry.Polygon `protobuf:"bytes,5,opt,name=polygon,proto3,oneof"`
}

func (*OcrAnnotation_BoundingBox) isOcrAnnotation_GeometryData() {}

func (*OcrAnnotation_Polygon) isOcrAnnotation_GeometryData() {}

type FocusArea struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  FocusAreaType          `protobuf:"varint,2,opt,name=type,proto3,enum=materialized_markup.FocusAreaType" json:"type,omitempty"`
	// Types that are valid to be assigned to GeometryData:
	//
	//	*FocusArea_BoundingBox
	//	*FocusArea_Polygon
	GeometryData  isFocusArea_GeometryData `protobuf_oneof:"geometry_data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FocusArea) Reset() {
	*x = FocusArea{}
	mi := &file_materialized_markup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FocusArea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocusArea) ProtoMessage() {}

func (x *FocusArea) ProtoReflect() protoreflect.Message {
	mi := &file_materialized_markup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocusArea.ProtoReflect.Descriptor instead.
func (*FocusArea) Descriptor() ([]byte, []int) {
	return file_materialized_markup_proto_rawDescGZIP(), []int{4}
}

func (x *FocusArea) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FocusArea) GetType() FocusAreaType {
	if x != nil {
		return x.Type
	}
	return FocusAreaType_FOCUS_AREA_TYPE_UNSPECIFIED
}

func (x *FocusArea) GetGeometryData() isFocusArea_GeometryData {
	if x != nil {
		return x.GeometryData
	}
	return nil
}

func (x *FocusArea) GetBoundingBox() *geometry.BoundingBox {
	if x != nil {
		if x, ok := x.GeometryData.(*FocusArea_BoundingBox); ok {
			return x.BoundingBox
		}
	}
	return nil
}

func (x *FocusArea) GetPolygon() *geometry.Polygon {
	if x != nil {
		if x, ok := x.GeometryData.(*FocusArea_Polygon); ok {
			return x.Polygon
		}
	}
	return nil
}

type isFocusArea_GeometryData interface {
	isFocusArea_GeometryData()
}

type FocusArea_BoundingBox struct {
	BoundingBox *geometry.BoundingBox `protobuf:"bytes,3,opt,name=bounding_box,json=boundingBox,proto3,oneof"`
}

type FocusArea_Polygon struct {
	Polygon *geometry.Polygon `protobuf:"bytes,4,opt,name=polygon,proto3,oneof"`
}

func (*FocusArea_BoundingBox) isFocusArea_GeometryData() {}

func (*FocusArea_Polygon) isFocusArea_GeometryData() {}

type MaterializedMarkup struct {
	state                           protoimpl.MessageState            `protogen:"open.v1"`
	Height                          int32                             `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Width                           int32                             `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	ClassificationAnnotations       []*ClassificationAnnotation       `protobuf:"bytes,3,rep,name=classification_annotations,json=classificationAnnotations,proto3" json:"classification_annotations,omitempty"`
	InstanceSegmentationAnnotations []*InstanceSegmentationAnnotation `protobuf:"bytes,4,rep,name=instance_segmentation_annotations,json=instanceSegmentationAnnotations,proto3" json:"instance_segmentation_annotations,omitempty"`
	ObjectDetectionAnnotations      []*ObjectDetectionAnnotation      `protobuf:"bytes,5,rep,name=object_detection_annotations,json=objectDetectionAnnotations,proto3" json:"object_detection_annotations,omitempty"`
	OcrAnnotations                  []*OcrAnnotation                  `protobuf:"bytes,6,rep,name=ocr_annotations,json=ocrAnnotations,proto3" json:"ocr_annotations,omitempty"`
	FocusAreas                      []*FocusArea                      `protobuf:"bytes,10,rep,name=focus_areas,json=focusAreas,proto3" json:"focus_areas,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *MaterializedMarkup) Reset() {
	*x = MaterializedMarkup{}
	mi := &file_materialized_markup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializedMarkup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializedMarkup) ProtoMessage() {}

func (x *MaterializedMarkup) ProtoReflect() protoreflect.Message {
	mi := &file_materialized_markup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializedMarkup.ProtoReflect.Descriptor instead.
func (*MaterializedMarkup) Descriptor() ([]byte, []int) {
	return file_materialized_markup_proto_rawDescGZIP(), []int{5}
}

func (x *MaterializedMarkup) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MaterializedMarkup) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MaterializedMarkup) GetClassificationAnnotations() []*ClassificationAnnotation {
	if x != nil {
		return x.ClassificationAnnotations
	}
	return nil
}

func (x *MaterializedMarkup) GetInstanceSegmentationAnnotations() []*InstanceSegmentationAnnotation {
	if x != nil {
		return x.InstanceSegmentationAnnotations
	}
	return nil
}

func (x *MaterializedMarkup) GetObjectDetectionAnnotations() []*ObjectDetectionAnnotation {
	if x != nil {
		return x.ObjectDetectionAnnotations
	}
	return nil
}

func (x *MaterializedMarkup) GetOcrAnnotations() []*OcrAnnotation {
	if x != nil {
		return x.OcrAnnotations
	}
	return nil
}

func (x *MaterializedMarkup) GetFocusAreas() []*FocusArea {
	if x != nil {
		return x.FocusAreas
	}
	return nil
}

var File_materialized_markup_proto protoreflect.FileDescriptor

const file_materialized_markup_proto_rawDesc = "" +
	"\n" +
	"\x19materialized_markup.proto\x12\x13materialized_markup\x1a\x0egeometry.proto\"[\n" +
	"\x18ClassificationAnnotation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\blabel_id\x18\x02 \x01(\tR\alabelId\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\"\xad\x01\n" +
	"\x1eInstanceSegmentationAnnotation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\blabel_id\x18\x02 \x01(\tR\alabelId\x12`\n" +
	"\x1ainstance_segmentation_mask\x18\x03 \x01(\v2\".geometry.InstanceSegmentationMaskR\x18instanceSegmentationMask\"\x80\x01\n" +
	"\x19ObjectDetectionAnnotation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\blabel_id\x18\x02 \x01(\tR\alabelId\x128\n" +
	"\fbounding_box\x18\x03 \x01(\v2\x15.geometry.BoundingBoxR\vboundingBox\"\xca\x01\n" +
	"\rOcrAnnotation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\blabel_id\x18\x02 \x01(\tR\alabelId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12:\n" +
	"\fbounding_box\x18\x04 \x01(\v2\x15.geometry.BoundingBoxH\x00R\vboundingBox\x12-\n" +
	"\apolygon\x18\x05 \x01(\v2\x11.geometry.PolygonH\x00R\apolygonB\x0f\n" +
	"\rgeometry_data\"\xcf\x01\n" +
	"\tFocusArea\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x04type\x18\x02 \x01(\x0e2\".materialized_markup.FocusAreaTypeR\x04type\x12:\n" +
	"\fbounding_box\x18\x03 \x01(\v2\x15.geometry.BoundingBoxH\x00R\vboundingBox\x12-\n" +
	"\apolygon\x18\x04 \x01(\v2\x11.geometry.PolygonH\x00R\apolygonB\x0f\n" +
	"\rgeometry_data\"\xb1\x04\n" +
	"\x12MaterializedMarkup\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x05R\x06height\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12l\n" +
	"\x1aclassification_annotations\x18\x03 \x03(\v2-.materialized_markup.ClassificationAnnotationR\x19classificationAnnotations\x12\x7f\n" +
	"!instance_segmentation_annotations\x18\x04 \x03(\v23.materialized_markup.InstanceSegmentationAnnotationR\x1finstanceSegmentationAnnotations\x12p\n" +
	"\x1cobject_detection_annotations\x18\x05 \x03(\v2..materialized_markup.ObjectDetectionAnnotationR\x1aobjectDetectionAnnotations\x12K\n" +
	"\x0focr_annotations\x18\x06 \x03(\v2\".materialized_markup.OcrAnnotationR\x0eocrAnnotations\x12?\n" +
	"\vfocus_areas\x18\n" +
	" \x03(\v2\x1e.materialized_markup.FocusAreaR\n" +
	"focusAreas*\x83\x01\n" +
	"\rFocusAreaType\x12\x1f\n" +
	"\x1bFOCUS_AREA_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18FOCUS_AREA_TYPE_NEGATIVE\x10\x01\x12\x1a\n" +
	"\x16FOCUS_AREA_TYPE_IGNORE\x10\x02\x12\x17\n" +
	"\x13FOCUS_AREA_TYPE_ROI\x10\x03BVZ4github.com/DENKweit/denkproto-go/materialized_markup\xaa\x02\x1dDENK.Proto.MaterializedMarkupb\x06proto3"

var (
	file_materialized_markup_proto_rawDescOnce sync.Once
	file_materialized_markup_proto_rawDescData []byte
)

func file_materialized_markup_proto_rawDescGZIP() []byte {
	file_materialized_markup_proto_rawDescOnce.Do(func() {
		file_materialized_markup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_materialized_markup_proto_rawDesc), len(file_materialized_markup_proto_rawDesc)))
	})
	return file_materialized_markup_proto_rawDescData
}

var file_materialized_markup_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_materialized_markup_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_materialized_markup_proto_goTypes = []any{
	(FocusAreaType)(0),                        // 0: materialized_markup.FocusAreaType
	(*ClassificationAnnotation)(nil),          // 1: materialized_markup.ClassificationAnnotation
	(*InstanceSegmentationAnnotation)(nil),    // 2: materialized_markup.InstanceSegmentationAnnotation
	(*ObjectDetectionAnnotation)(nil),         // 3: materialized_markup.ObjectDetectionAnnotation
	(*OcrAnnotation)(nil),                     // 4: materialized_markup.OcrAnnotation
	(*FocusArea)(nil),                         // 5: materialized_markup.FocusArea
	(*MaterializedMarkup)(nil),                // 6: materialized_markup.MaterializedMarkup
	(*geometry.InstanceSegmentationMask)(nil), // 7: geometry.InstanceSegmentationMask
	(*geometry.BoundingBox)(nil),              // 8: geometry.BoundingBox
	(*geometry.Polygon)(nil),                  // 9: geometry.Polygon
}
var file_materialized_markup_proto_depIdxs = []int32{
	7,  // 0: materialized_markup.InstanceSegmentationAnnotation.instance_segmentation_mask:type_name -> geometry.InstanceSegmentationMask
	8,  // 1: materialized_markup.ObjectDetectionAnnotation.bounding_box:type_name -> geometry.BoundingBox
	8,  // 2: materialized_markup.OcrAnnotation.bounding_box:type_name -> geometry.BoundingBox
	9,  // 3: materialized_markup.OcrAnnotation.polygon:type_name -> geometry.Polygon
	0,  // 4: materialized_markup.FocusArea.type:type_name -> materialized_markup.FocusAreaType
	8,  // 5: materialized_markup.FocusArea.bounding_box:type_name -> geometry.BoundingBox
	9,  // 6: materialized_markup.FocusArea.polygon:type_name -> geometry.Polygon
	1,  // 7: materialized_markup.MaterializedMarkup.classification_annotations:type_name -> materialized_markup.ClassificationAnnotation
	2,  // 8: materialized_markup.MaterializedMarkup.instance_segmentation_annotations:type_name -> materialized_markup.InstanceSegmentationAnnotation
	3,  // 9: materialized_markup.MaterializedMarkup.object_detection_annotations:type_name -> materialized_markup.ObjectDetectionAnnotation
	4,  // 10: materialized_markup.MaterializedMarkup.ocr_annotations:type_name -> materialized_markup.OcrAnnotation
	5,  // 11: materialized_markup.MaterializedMarkup.focus_areas:type_name -> materialized_markup.FocusArea
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_materialized_markup_proto_init() }
func file_materialized_markup_proto_init() {
	if File_materialized_markup_proto != nil {
		return
	}
	file_materialized_markup_proto_msgTypes[3].OneofWrappers = []any{
		(*OcrAnnotation_BoundingBox)(nil),
		(*OcrAnnotation_Polygon)(nil),
	}
	file_materialized_markup_proto_msgTypes[4].OneofWrappers = []any{
		(*FocusArea_BoundingBox)(nil),
		(*FocusArea_Polygon)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_materialized_markup_proto_rawDesc), len(file_materialized_markup_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_materialized_markup_proto_goTypes,
		DependencyIndexes: file_materialized_markup_proto_depIdxs,
		EnumInfos:         file_materialized_markup_proto_enumTypes,
		MessageInfos:      file_materialized_markup_proto_msgTypes,
	}.Build()
	File_materialized_markup_proto = out.File
	file_materialized_markup_proto_goTypes = nil
	file_materialized_markup_proto_depIdxs = nil
}
