// This file should only ever be modified in a backwards compatible way.
// If unsure, consult https://protobuf.dev/programming-guides/proto3/

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: file_metadata.proto

package file_metadata

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileType int32

const (
	FileType_FT_UNDEFINED FileType = 0
	FileType_FT_DENKMODEL FileType = 1
	FileType_FT_DENKFLOW  FileType = 2
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "FT_UNDEFINED",
		1: "FT_DENKMODEL",
		2: "FT_DENKFLOW",
	}
	FileType_value = map[string]int32{
		"FT_UNDEFINED": 0,
		"FT_DENKMODEL": 1,
		"FT_DENKFLOW":  2,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_file_metadata_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_file_metadata_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_file_metadata_proto_rawDescGZIP(), []int{0}
}

type FileMetadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FileType          FileType               `protobuf:"varint,1,opt,name=file_type,json=fileType,proto3,enum=file_metadata.FileType" json:"file_type,omitempty"`
	FileFormatVersion uint32                 `protobuf:"varint,2,opt,name=file_format_version,json=fileFormatVersion,proto3" json:"file_format_version,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                     // Unix timestamp in seconds
	DenkprotoVersion  string                 `protobuf:"bytes,4,opt,name=denkproto_version,json=denkprotoVersion,proto3" json:"denkproto_version,omitempty"` // Version in the form 0.0.0, 0.0.0-a0, 0.0.0-b0 or 0.0.0-rc0
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_file_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_file_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_file_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *FileMetadata) GetFileType() FileType {
	if x != nil {
		return x.FileType
	}
	return FileType_FT_UNDEFINED
}

func (x *FileMetadata) GetFileFormatVersion() uint32 {
	if x != nil {
		return x.FileFormatVersion
	}
	return 0
}

func (x *FileMetadata) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FileMetadata) GetDenkprotoVersion() string {
	if x != nil {
		return x.DenkprotoVersion
	}
	return ""
}

type FileMetadataContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileMetadata  *FileMetadata          `protobuf:"bytes,1024,opt,name=file_metadata,json=fileMetadata,proto3" json:"file_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadataContainer) Reset() {
	*x = FileMetadataContainer{}
	mi := &file_file_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadataContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadataContainer) ProtoMessage() {}

func (x *FileMetadataContainer) ProtoReflect() protoreflect.Message {
	mi := &file_file_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadataContainer.ProtoReflect.Descriptor instead.
func (*FileMetadataContainer) Descriptor() ([]byte, []int) {
	return file_file_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *FileMetadataContainer) GetFileMetadata() *FileMetadata {
	if x != nil {
		return x.FileMetadata
	}
	return nil
}

var File_file_metadata_proto protoreflect.FileDescriptor

const file_file_metadata_proto_rawDesc = "" +
	"\n" +
	"\x13file_metadata.proto\x12\rfile_metadata\x1a\x0evalidate.proto\"\xed\x01\n" +
	"\fFileMetadata\x124\n" +
	"\tfile_type\x18\x01 \x01(\x0e2\x17.file_metadata.FileTypeR\bfileType\x12.\n" +
	"\x13file_format_version\x18\x02 \x01(\rR\x11fileFormatVersion\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12X\n" +
	"\x11denkproto_version\x18\x04 \x01(\tB+\xfaB(r&2$^\\d+\\.\\d+\\.\\d+(-a\\d+|-b\\d+|-rc\\d+)?$R\x10denkprotoVersion\"Z\n" +
	"\x15FileMetadataContainer\x12A\n" +
	"\rfile_metadata\x18\x80\b \x01(\v2\x1b.file_metadata.FileMetadataR\ffileMetadata*?\n" +
	"\bFileType\x12\x10\n" +
	"\fFT_UNDEFINED\x10\x00\x12\x10\n" +
	"\fFT_DENKMODEL\x10\x01\x12\x0f\n" +
	"\vFT_DENKFLOW\x10\x02BJZ.github.com/DENKweit/denkproto-go/file_metadata\xaa\x02\x17DENK.Proto.FileMetadatab\x06proto3"

var (
	file_file_metadata_proto_rawDescOnce sync.Once
	file_file_metadata_proto_rawDescData []byte
)

func file_file_metadata_proto_rawDescGZIP() []byte {
	file_file_metadata_proto_rawDescOnce.Do(func() {
		file_file_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_metadata_proto_rawDesc), len(file_file_metadata_proto_rawDesc)))
	})
	return file_file_metadata_proto_rawDescData
}

var file_file_metadata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_file_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_file_metadata_proto_goTypes = []any{
	(FileType)(0),                 // 0: file_metadata.FileType
	(*FileMetadata)(nil),          // 1: file_metadata.FileMetadata
	(*FileMetadataContainer)(nil), // 2: file_metadata.FileMetadataContainer
}
var file_file_metadata_proto_depIdxs = []int32{
	0, // 0: file_metadata.FileMetadata.file_type:type_name -> file_metadata.FileType
	1, // 1: file_metadata.FileMetadataContainer.file_metadata:type_name -> file_metadata.FileMetadata
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_file_metadata_proto_init() }
func file_file_metadata_proto_init() {
	if File_file_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_metadata_proto_rawDesc), len(file_file_metadata_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_metadata_proto_goTypes,
		DependencyIndexes: file_file_metadata_proto_depIdxs,
		EnumInfos:         file_file_metadata_proto_enumTypes,
		MessageInfos:      file_file_metadata_proto_msgTypes,
	}.Build()
	File_file_metadata_proto = out.File
	file_file_metadata_proto_goTypes = nil
	file_file_metadata_proto_depIdxs = nil
}
